/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppXmatrixRouteImport } from './routes/_app/xmatrix'
import { Route as AppWsjfRouteImport } from './routes/_app/wsjf'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as AppLbcRouteImport } from './routes/_app/lbc'
import { Route as AppKanbanRouteImport } from './routes/_app/kanban'
import { Route as AppLbcIndexRouteImport } from './routes/_app/lbc.index'
import { Route as AppLbcNewRouteImport } from './routes/_app/lbc.new'
import { Route as AppLbcIdRouteImport } from './routes/_app/lbc.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppXmatrixRoute = AppXmatrixRouteImport.update({
  id: '/xmatrix',
  path: '/xmatrix',
  getParentRoute: () => AppRoute,
} as any)
const AppWsjfRoute = AppWsjfRouteImport.update({
  id: '/wsjf',
  path: '/wsjf',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppLbcRoute = AppLbcRouteImport.update({
  id: '/lbc',
  path: '/lbc',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppLbcIndexRoute = AppLbcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLbcRoute,
} as any)
const AppLbcNewRoute = AppLbcNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLbcRoute,
} as any)
const AppLbcIdRoute = AppLbcIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLbcRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/kanban': typeof AppKanbanRoute
  '/lbc': typeof AppLbcRouteWithChildren
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/wsjf': typeof AppWsjfRoute
  '/xmatrix': typeof AppXmatrixRoute
  '/lbc/$id': typeof AppLbcIdRoute
  '/lbc/new': typeof AppLbcNewRoute
  '/lbc/': typeof AppLbcIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/kanban': typeof AppKanbanRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/wsjf': typeof AppWsjfRoute
  '/xmatrix': typeof AppXmatrixRoute
  '/lbc/$id': typeof AppLbcIdRoute
  '/lbc/new': typeof AppLbcNewRoute
  '/lbc': typeof AppLbcIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/kanban': typeof AppKanbanRoute
  '/_app/lbc': typeof AppLbcRouteWithChildren
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/wsjf': typeof AppWsjfRoute
  '/_app/xmatrix': typeof AppXmatrixRoute
  '/_app/lbc/$id': typeof AppLbcIdRoute
  '/_app/lbc/new': typeof AppLbcNewRoute
  '/_app/lbc/': typeof AppLbcIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/kanban'
    | '/lbc'
    | '/portfolio'
    | '/settings'
    | '/wsjf'
    | '/xmatrix'
    | '/lbc/$id'
    | '/lbc/new'
    | '/lbc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/kanban'
    | '/portfolio'
    | '/settings'
    | '/wsjf'
    | '/xmatrix'
    | '/lbc/$id'
    | '/lbc/new'
    | '/lbc'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/kanban'
    | '/_app/lbc'
    | '/_app/portfolio'
    | '/_app/settings'
    | '/_app/wsjf'
    | '/_app/xmatrix'
    | '/_app/lbc/$id'
    | '/_app/lbc/new'
    | '/_app/lbc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/xmatrix': {
      id: '/_app/xmatrix'
      path: '/xmatrix'
      fullPath: '/xmatrix'
      preLoaderRoute: typeof AppXmatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wsjf': {
      id: '/_app/wsjf'
      path: '/wsjf'
      fullPath: '/wsjf'
      preLoaderRoute: typeof AppWsjfRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lbc': {
      id: '/_app/lbc'
      path: '/lbc'
      fullPath: '/lbc'
      preLoaderRoute: typeof AppLbcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lbc/': {
      id: '/_app/lbc/'
      path: '/'
      fullPath: '/lbc/'
      preLoaderRoute: typeof AppLbcIndexRouteImport
      parentRoute: typeof AppLbcRoute
    }
    '/_app/lbc/new': {
      id: '/_app/lbc/new'
      path: '/new'
      fullPath: '/lbc/new'
      preLoaderRoute: typeof AppLbcNewRouteImport
      parentRoute: typeof AppLbcRoute
    }
    '/_app/lbc/$id': {
      id: '/_app/lbc/$id'
      path: '/$id'
      fullPath: '/lbc/$id'
      preLoaderRoute: typeof AppLbcIdRouteImport
      parentRoute: typeof AppLbcRoute
    }
  }
}

interface AppLbcRouteChildren {
  AppLbcIdRoute: typeof AppLbcIdRoute
  AppLbcNewRoute: typeof AppLbcNewRoute
  AppLbcIndexRoute: typeof AppLbcIndexRoute
}

const AppLbcRouteChildren: AppLbcRouteChildren = {
  AppLbcIdRoute: AppLbcIdRoute,
  AppLbcNewRoute: AppLbcNewRoute,
  AppLbcIndexRoute: AppLbcIndexRoute,
}

const AppLbcRouteWithChildren =
  AppLbcRoute._addFileChildren(AppLbcRouteChildren)

interface AppRouteChildren {
  AppKanbanRoute: typeof AppKanbanRoute
  AppLbcRoute: typeof AppLbcRouteWithChildren
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWsjfRoute: typeof AppWsjfRoute
  AppXmatrixRoute: typeof AppXmatrixRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKanbanRoute: AppKanbanRoute,
  AppLbcRoute: AppLbcRouteWithChildren,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWsjfRoute: AppWsjfRoute,
  AppXmatrixRoute: AppXmatrixRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
