/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppXmatrixRouteImport } from './routes/_app/xmatrix'
import { Route as AppWsjfRouteImport } from './routes/_app/wsjf'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppPortfolioRouteImport } from './routes/_app/portfolio'
import { Route as AppLbcRouteImport } from './routes/_app/lbc'
import { Route as AppKanbanRouteImport } from './routes/_app/kanban'
import { Route as AppAssetsRouteImport } from './routes/_app/assets'
import { Route as AppLbcIndexRouteImport } from './routes/_app/lbc.index'
import { Route as AppKanbanIndexRouteImport } from './routes/_app/kanban.index'
import { Route as AppAssetsIndexRouteImport } from './routes/_app/assets.index'
import { Route as AppLbcNewRouteImport } from './routes/_app/lbc.new'
import { Route as AppLbcIdRouteImport } from './routes/_app/lbc.$id'
import { Route as AppKanbanClosedRouteImport } from './routes/_app/kanban.closed'
import { Route as AppKanbanArchiveRouteImport } from './routes/_app/kanban.archive'
import { Route as AppKanbanActiveRouteImport } from './routes/_app/kanban.active'
import { Route as AppAssetsIdRouteImport } from './routes/_app/assets.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppXmatrixRoute = AppXmatrixRouteImport.update({
  id: '/xmatrix',
  path: '/xmatrix',
  getParentRoute: () => AppRoute,
} as any)
const AppWsjfRoute = AppWsjfRouteImport.update({
  id: '/wsjf',
  path: '/wsjf',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppPortfolioRoute = AppPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppLbcRoute = AppLbcRouteImport.update({
  id: '/lbc',
  path: '/lbc',
  getParentRoute: () => AppRoute,
} as any)
const AppKanbanRoute = AppKanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppLbcIndexRoute = AppLbcIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLbcRoute,
} as any)
const AppKanbanIndexRoute = AppKanbanIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppKanbanRoute,
} as any)
const AppAssetsIndexRoute = AppAssetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAssetsRoute,
} as any)
const AppLbcNewRoute = AppLbcNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppLbcRoute,
} as any)
const AppLbcIdRoute = AppLbcIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppLbcRoute,
} as any)
const AppKanbanClosedRoute = AppKanbanClosedRouteImport.update({
  id: '/closed',
  path: '/closed',
  getParentRoute: () => AppKanbanRoute,
} as any)
const AppKanbanArchiveRoute = AppKanbanArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AppKanbanRoute,
} as any)
const AppKanbanActiveRoute = AppKanbanActiveRouteImport.update({
  id: '/active',
  path: '/active',
  getParentRoute: () => AppKanbanRoute,
} as any)
const AppAssetsIdRoute = AppAssetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAssetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/assets': typeof AppAssetsRouteWithChildren
  '/kanban': typeof AppKanbanRouteWithChildren
  '/lbc': typeof AppLbcRouteWithChildren
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/wsjf': typeof AppWsjfRoute
  '/xmatrix': typeof AppXmatrixRoute
  '/assets/$id': typeof AppAssetsIdRoute
  '/kanban/active': typeof AppKanbanActiveRoute
  '/kanban/archive': typeof AppKanbanArchiveRoute
  '/kanban/closed': typeof AppKanbanClosedRoute
  '/lbc/$id': typeof AppLbcIdRoute
  '/lbc/new': typeof AppLbcNewRoute
  '/assets/': typeof AppAssetsIndexRoute
  '/kanban/': typeof AppKanbanIndexRoute
  '/lbc/': typeof AppLbcIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/portfolio': typeof AppPortfolioRoute
  '/settings': typeof AppSettingsRoute
  '/wsjf': typeof AppWsjfRoute
  '/xmatrix': typeof AppXmatrixRoute
  '/assets/$id': typeof AppAssetsIdRoute
  '/kanban/active': typeof AppKanbanActiveRoute
  '/kanban/archive': typeof AppKanbanArchiveRoute
  '/kanban/closed': typeof AppKanbanClosedRoute
  '/lbc/$id': typeof AppLbcIdRoute
  '/lbc/new': typeof AppLbcNewRoute
  '/assets': typeof AppAssetsIndexRoute
  '/kanban': typeof AppKanbanIndexRoute
  '/lbc': typeof AppLbcIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/assets': typeof AppAssetsRouteWithChildren
  '/_app/kanban': typeof AppKanbanRouteWithChildren
  '/_app/lbc': typeof AppLbcRouteWithChildren
  '/_app/portfolio': typeof AppPortfolioRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/wsjf': typeof AppWsjfRoute
  '/_app/xmatrix': typeof AppXmatrixRoute
  '/_app/assets/$id': typeof AppAssetsIdRoute
  '/_app/kanban/active': typeof AppKanbanActiveRoute
  '/_app/kanban/archive': typeof AppKanbanArchiveRoute
  '/_app/kanban/closed': typeof AppKanbanClosedRoute
  '/_app/lbc/$id': typeof AppLbcIdRoute
  '/_app/lbc/new': typeof AppLbcNewRoute
  '/_app/assets/': typeof AppAssetsIndexRoute
  '/_app/kanban/': typeof AppKanbanIndexRoute
  '/_app/lbc/': typeof AppLbcIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/assets'
    | '/kanban'
    | '/lbc'
    | '/portfolio'
    | '/settings'
    | '/wsjf'
    | '/xmatrix'
    | '/assets/$id'
    | '/kanban/active'
    | '/kanban/archive'
    | '/kanban/closed'
    | '/lbc/$id'
    | '/lbc/new'
    | '/assets/'
    | '/kanban/'
    | '/lbc/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/portfolio'
    | '/settings'
    | '/wsjf'
    | '/xmatrix'
    | '/assets/$id'
    | '/kanban/active'
    | '/kanban/archive'
    | '/kanban/closed'
    | '/lbc/$id'
    | '/lbc/new'
    | '/assets'
    | '/kanban'
    | '/lbc'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/assets'
    | '/_app/kanban'
    | '/_app/lbc'
    | '/_app/portfolio'
    | '/_app/settings'
    | '/_app/wsjf'
    | '/_app/xmatrix'
    | '/_app/assets/$id'
    | '/_app/kanban/active'
    | '/_app/kanban/archive'
    | '/_app/kanban/closed'
    | '/_app/lbc/$id'
    | '/_app/lbc/new'
    | '/_app/assets/'
    | '/_app/kanban/'
    | '/_app/lbc/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/xmatrix': {
      id: '/_app/xmatrix'
      path: '/xmatrix'
      fullPath: '/xmatrix'
      preLoaderRoute: typeof AppXmatrixRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wsjf': {
      id: '/_app/wsjf'
      path: '/wsjf'
      fullPath: '/wsjf'
      preLoaderRoute: typeof AppWsjfRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/portfolio': {
      id: '/_app/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AppPortfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lbc': {
      id: '/_app/lbc'
      path: '/lbc'
      fullPath: '/lbc'
      preLoaderRoute: typeof AppLbcRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kanban': {
      id: '/_app/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof AppKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lbc/': {
      id: '/_app/lbc/'
      path: '/'
      fullPath: '/lbc/'
      preLoaderRoute: typeof AppLbcIndexRouteImport
      parentRoute: typeof AppLbcRoute
    }
    '/_app/kanban/': {
      id: '/_app/kanban/'
      path: '/'
      fullPath: '/kanban/'
      preLoaderRoute: typeof AppKanbanIndexRouteImport
      parentRoute: typeof AppKanbanRoute
    }
    '/_app/assets/': {
      id: '/_app/assets/'
      path: '/'
      fullPath: '/assets/'
      preLoaderRoute: typeof AppAssetsIndexRouteImport
      parentRoute: typeof AppAssetsRoute
    }
    '/_app/lbc/new': {
      id: '/_app/lbc/new'
      path: '/new'
      fullPath: '/lbc/new'
      preLoaderRoute: typeof AppLbcNewRouteImport
      parentRoute: typeof AppLbcRoute
    }
    '/_app/lbc/$id': {
      id: '/_app/lbc/$id'
      path: '/$id'
      fullPath: '/lbc/$id'
      preLoaderRoute: typeof AppLbcIdRouteImport
      parentRoute: typeof AppLbcRoute
    }
    '/_app/kanban/closed': {
      id: '/_app/kanban/closed'
      path: '/closed'
      fullPath: '/kanban/closed'
      preLoaderRoute: typeof AppKanbanClosedRouteImport
      parentRoute: typeof AppKanbanRoute
    }
    '/_app/kanban/archive': {
      id: '/_app/kanban/archive'
      path: '/archive'
      fullPath: '/kanban/archive'
      preLoaderRoute: typeof AppKanbanArchiveRouteImport
      parentRoute: typeof AppKanbanRoute
    }
    '/_app/kanban/active': {
      id: '/_app/kanban/active'
      path: '/active'
      fullPath: '/kanban/active'
      preLoaderRoute: typeof AppKanbanActiveRouteImport
      parentRoute: typeof AppKanbanRoute
    }
    '/_app/assets/$id': {
      id: '/_app/assets/$id'
      path: '/$id'
      fullPath: '/assets/$id'
      preLoaderRoute: typeof AppAssetsIdRouteImport
      parentRoute: typeof AppAssetsRoute
    }
  }
}

interface AppAssetsRouteChildren {
  AppAssetsIdRoute: typeof AppAssetsIdRoute
  AppAssetsIndexRoute: typeof AppAssetsIndexRoute
}

const AppAssetsRouteChildren: AppAssetsRouteChildren = {
  AppAssetsIdRoute: AppAssetsIdRoute,
  AppAssetsIndexRoute: AppAssetsIndexRoute,
}

const AppAssetsRouteWithChildren = AppAssetsRoute._addFileChildren(
  AppAssetsRouteChildren,
)

interface AppKanbanRouteChildren {
  AppKanbanActiveRoute: typeof AppKanbanActiveRoute
  AppKanbanArchiveRoute: typeof AppKanbanArchiveRoute
  AppKanbanClosedRoute: typeof AppKanbanClosedRoute
  AppKanbanIndexRoute: typeof AppKanbanIndexRoute
}

const AppKanbanRouteChildren: AppKanbanRouteChildren = {
  AppKanbanActiveRoute: AppKanbanActiveRoute,
  AppKanbanArchiveRoute: AppKanbanArchiveRoute,
  AppKanbanClosedRoute: AppKanbanClosedRoute,
  AppKanbanIndexRoute: AppKanbanIndexRoute,
}

const AppKanbanRouteWithChildren = AppKanbanRoute._addFileChildren(
  AppKanbanRouteChildren,
)

interface AppLbcRouteChildren {
  AppLbcIdRoute: typeof AppLbcIdRoute
  AppLbcNewRoute: typeof AppLbcNewRoute
  AppLbcIndexRoute: typeof AppLbcIndexRoute
}

const AppLbcRouteChildren: AppLbcRouteChildren = {
  AppLbcIdRoute: AppLbcIdRoute,
  AppLbcNewRoute: AppLbcNewRoute,
  AppLbcIndexRoute: AppLbcIndexRoute,
}

const AppLbcRouteWithChildren =
  AppLbcRoute._addFileChildren(AppLbcRouteChildren)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRouteWithChildren
  AppKanbanRoute: typeof AppKanbanRouteWithChildren
  AppLbcRoute: typeof AppLbcRouteWithChildren
  AppPortfolioRoute: typeof AppPortfolioRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWsjfRoute: typeof AppWsjfRoute
  AppXmatrixRoute: typeof AppXmatrixRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRouteWithChildren,
  AppKanbanRoute: AppKanbanRouteWithChildren,
  AppLbcRoute: AppLbcRouteWithChildren,
  AppPortfolioRoute: AppPortfolioRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWsjfRoute: AppWsjfRoute,
  AppXmatrixRoute: AppXmatrixRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
